//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zavod.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks
    {
        public long Id { get; set; }
        public long ProductId { get; set; }
        public int Available { get; set; }
        public int Price { get; set; }
    
        public virtual Products Product { get; set; }
    }
}
